name: Pack and Upload node_modules to Google Drive

on:
  workflow_dispatch: # 允许你手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库中的配置文件（rclone.conf, package.json 等）
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ 安装 rclone 工具
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      # 3️⃣ 部署 rclone 授权凭证
      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          cp rclone.conf ~/.config/rclone/rclone.conf

      # 下载 deb 包
      - name: Download TimescaleDB deb
        run: |
          wget -O timescaledb.deb \
          "https://packagecloud.io/timescale/timescaledb/packages/debian/bullseye/timescaledb-2-2.18.1-postgresql-16_2.18.1~debian11_amd64.deb/download.deb?distro_version_id=207"

      - name: Check file
        run: |
          ls -lh timescaledb.deb

      - name: Upload to Google Drive
        run: |
          rclone mkdir Google:/Node_Deps_Backup || true
          rclone copy timescaledb.deb Google:/Node_Deps_Backup/ --progress
          rclone lsf Google:/Node_Deps_Backup/
